# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stella Codes
email: stellacodes2.0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Things about writing code, learning technology, and having fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stellacodes.github.io" # the base hostname & protocol for your site
twitter_username: stellacodes
github_username:  stellacodes

# Build settings
markdown: kramdown
